### ISSUE TITLE
Easy to use?

### ISSUE THREAD

**Issue by abnerh69** [gulliverbms/django_grapesjs#1]
@gulliverbms, Hi!  Maybe django_grapesjs is too easy to use.  I am trying right now.  Let me know if there is something I can help.

**Comment by gulliverbms** [comment]
@abnerh69, Hi. If there are any problems in using or if you have ideas, let me know in more detail.

**Comment by abnerh69** [comment]
Hey @gulliverbms.  Yes.  There is a little problem... after install and
make a little modification to my newmodel, then I tried to insert a new
record in database but got a exception:
TypeError at /en/admin/testproject/newmodel/add/

'bool' object is not callable

Request Method: POST
Request URL: http://127.0.0.1:8000/es/admin/testproject/newmodel/add/
Django Version: 1.11.13
Exception Type: TypeError
Exception Value:

'bool' object is not callable

Exception Location:
/Users/username/Desktop/d/testproject/lib/python3.6/site-packages/django/forms/fields.py
in clean, line 161
Python Executable: /Users/username/Desktop/d/testproject/bin/python
Python Version: 3.6.4
Python Path:

['/Users/username/Desktop/d/testproject',
 '/Users/username/Desktop/d/testproject/lib/python36.zip',
 '/Users/username/Desktop/d/testproject/lib/python3.6',
 '/Users/username/Desktop/d/testproject/lib/python3.6/lib-dynload',
 '/Users/username/miniconda3/lib/python3.6',
 '/Users/username/Desktop/d/testproject/lib/python3.6/site-packages']


Any idea?

Besides, how can I integrate with django-cms?  Is it possible to integrate
with custom models?

Thanks a lot.

**Comment by gulliverbms** [comment]
fixed in 1aca2105a18dcff3447c902af6fb17e555a502bc

**Comment by gulliverbms** [comment]
@abnerh69, i can not give an unambiguous answer about cms. But if you check and identify errors, and also report them - I'll be happy. Thank you
